application: clock
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /prefs
  script: prefs.application
  login: required
  
- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest